apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-demo.fullname" . }}
  namespace: {{ include "django-demo.namespace" . }}
data:
  DJANGO_ALLOWED_HOSTS: {{ .Values.djangoAllowedHosts | quote}}
  DEBUG: {{ .Values.djangoDebug | quote }}