apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "django-demo.fullname" . }}
  labels:
    {{- include "django-demo.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  volumeMode: Filesystem
  {{- with .Values.pvc.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage}}