apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-demo.fullname" . }}
  namespace: {{ include "django-demo.namespace" . }}
data:
  DATABASE_URL: {{ .Values.databaseURL | b64enc | quote }}