apiVersion: v2
name: django-demo
description: A Helm chart for Kubernetes

type: application

version: 0.1.1

appVersion: "1.0-stable"

dependencies:
- name: ingress-nginx
  version: "4.8.1"
  repository: "https://kubernetes.github.io/ingress-nginx"

- name: cert-manager
  version: "v1.13.1"
  repository: "https://charts.jetstack.io"
  
- name: metrics-server
  version: "3.11.0"
  repository: "https://kubernetes-sigs.github.io/metrics-server/"
